name: npm publish production

on:
  push:
    branches: 
      - master

jobs:
  publish-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1


      - name: Set up Node.js for NPM
        uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"
          scope: '@pinpt'
          node-version: '10.x'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:
            
      - name: Install dependencies
        run: npm install --ignore-scripts
        env:
          UIC_NPM_TOKEN: ${{ secrets.UIC_NPM_TOKEN }}
          
      - name: Publish package to NPM
        run: npm publish --access public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          UIC_NPM_TOKEN: ${{ secrets.UIC_NPM_TOKEN }}

